pollutantmean(specdir, "sulfate", 1:10)
pollutantmean(specdir, "nitrate", 70:72)
pollutantmean(specdir, "sulfate", 34)
pollutantmean(specdir, "nitrate")

id1<-c(6, 10, 20, 34, 100, 200, 310)
cc<-complete(specdir,id1)
print(cc$nobs)

cc<-complete(specdir,54)
print(cc$nobs)

RNGversion("3.5.1")  
set.seed(42)
cc <- complete(specdir, 332:1)
use <- sample(332, 10)
print(cc[use, "nobs"])

cr <- corr("specdata")                
cr <- sort(cr)   
RNGversion("3.5.1")
set.seed(868)                
out <- round(cr[sample(length(cr), 5)], 4)
print(out)

cr <- corr("specdata", 129)                
cr <- sort(cr)                
n <- length(cr)    
RNGversion("3.5.1")
set.seed(197)                
out <- c(n, round(cr[sample(n, 5)], 4))
print(out)

cr <- corr("specdata", 2000)                
n <- length(cr)                
cr <- corr("specdata", 1000)                
cr <- sort(cr)
print(c(n, round(cr, 4)))